# Generated by Django 5.2.12 on 2026-04-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corun_app', '0002_sitecontent_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdefinition',
            options={'ordering': ['-modified_at']},
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(default='published', max_length=50),
        ),
    ]
