# Generated by Django 5.2.12 on 2026-04-02 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corun_app', '0004_comment_prompt_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddIndex(
            model_name='sitecontent',
            index=models.Index(fields=['slug', '-version'], name='corun_app_s_slug_cc16a9_idx'),
        ),
    ]
