# Generated by Codex on 2026-05-08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corun_app', '0007_jobnotificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_group_id', models.UUIDField(db_index=True)),
                ('tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag_name'],
                'indexes': [
                    models.Index(fields=['tag_name'], name='idx_page_tags_tag_name'),
                    models.Index(fields=['page_group_id', 'tag_name'], name='idx_page_tags_group_tag'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=['page_group_id', 'tag_name'], name='unique_page_group_tag'),
                ],
            },
        ),
    ]
